### ISSUE TITLE
Example Webpack Integration

### ISSUE THREAD

**Issue by ghost** [Vheissu/aurelia-typescript-plugin#1]
Can you show an example of what the Webpack support would look like in `packages.json`?

**Comment by Vheissu** [comment]
There isn't really anything needed other than defining non-included/potentially dynamic resources under aurelia>build>resources in the package.json :)

**Comment by HamedFathi** [comment]
Can you give an example in this case? for example use [toastr](https://github.com/CodeSeven/toastr) How to add it ?
