### ISSUE TITLE
Cannot npm install after clone

### ISSUE THREAD

**Issue by RicoSuter** [Vheissu/aurelia-typescript-plugin#4]
After cloning the repo and running "npm i" (no changes), I get this error: 

![image](https://user-images.githubusercontent.com/2603405/31024804-80a14704-a540-11e7-875b-ebcdee73abfc.png)

Any ideas?

**Comment by RicoSuter** [comment]
It seems that it only works with yarn, is it possible to make this work with npm?

**Comment by Vheissu** [comment]
Let me check this out for you. It should work with both Yarn and Npm.

**Comment by Vheissu** [comment]
Just confirmed with latest updates that Npm and Yarn both work as expected. Reopen this one if you encounter it again though and I'll dig deeper.

**Comment by RicoSuter** [comment]
Thank you very much. I managed to build the package: https://github.com/RSuter/aurelia-bs

However I have two issues:

1. When starting the demo app, I have to hit F5 twice before new changes are available in the browser: https://github.com/RSuter/aurelia-bs/issues/2
2. I cannot find a way to define module IDs which work in the demo and in the published NPM package: https://github.com/RSuter/aurelia-bs/issues/6

Would be cool if you have some ideas to fix these...

Thank you for your starter project!
