### ISSUE TITLE
How to use this with a service?

### ISSUE THREAD

**Issue by mbx-mbx** [Vheissu/aurelia-typescript-plugin#7]
I have currently got this up and running with npm link and a simple custom element which gets registered globally in the plugin itself. This works fine and I can use the custom element in the consuming project. 

The next thing I want to to is to create and export a service for use in the consuming project. At present it is a simple service (MessageService - in a src -> resources -> services folder ), it just has one method that returns a string. It gets compiled fine, and outputted into the dist folder but I cannot import this service into the consuming project. How do we get this to work?

Many thanks.

**Comment by Vheissu** [comment]
Hi Matt,

Thanks for checking out the plugin skeleton. The approach you're after is exporting it from the main index.ts file which will make your service importable in the consuming app.

Something along the lines of this in the main index file:

```
export {myService} from "./my-service";
````

You can also do a wildcard export like this:

```
export * from "./my-service";
````

**Comment by mbx-mbx** [comment]
Thank you very much for the quick reply. it is working now apart from one Typescript issue in my editor in the consuming project,

````
TS2305: Module '".*path*/node_modules/aurelia-typescript-plugin/dist/commonjs"' has no exported member 'MessageService'
````

It all builds and works fine however! Any ideas?

I can see the export in the generated js however:

````
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./styles.css");
var aurelia_pal_1 = require("aurelia-pal");
var messageService_1 = require("./resources/services/messageService");
exports.MessageService = messageService_1.MessageService;
var elements = [aurelia_pal_1.PLATFORM.moduleName('./resources/elements/test-element/testElement')];
function configure(aurelia) {
    aurelia.globalResources(elements.slice());
}
exports.configure = configure;
//# sourceMappingURL=index.js.map
````

EDIT:
This error seems to go away if i npm pack and then npm install the plugin, so might just be a quirk.
